
import Head from 'next/head';
import Header from '../components/Header/Header';
// import Hero from '../components/Hero/Hero'
// import Popular from '../components/Popular/Popular'

export default function Home() {
	return (
		<>
			<Head>
				<title>Intex shop</title>
				<meta name='description' content='Generated by create next app' />
				<link rel='icon' href={''} />
			</Head>
			<Header /> {/*Nurillo Headerni oldi*/}
			{/* <Hero/> Nurillo Hero oldi */}
			{/* <Popular/> Nozimjon Популярные товары oldi */}
		</>
	);

import Head from 'next/head'
import Header from '../components/Header/Header'
import Hero from '../components/Hero/Hero'
import Popular from '../components/Popular/Popular'
import SiteLogo from '../public/Assets/Images/i-logo.svg'
import { useSelector } from 'react-redux'

export default function Home() {
  const categories = useSelector((state) => state.data)
  console.log(categories)
  return (
    <div>
      <Head>
        <title>Intex shop</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href={SiteLogo} />
      </Head>
      {/* <Header/> Nurillo Headerni oldi  */}
      <Hero /> {/*Nurillo Hero oldi*/}
      <Popular /> {/*Nozimjon Популярные товары oldi*/}
      <h1 className="text-green-transparent text-center text-5xl font-bold text-black-black_dark w-426 ">
        Бассейны от intex в Ташкенте
      </h1>
      <div className="flex">
        {categories.length &&
          categories.map((category) => {
            return (
              <div key={category.id}>
                <ul>
                  <li
                    className={
                      category.status === 'Хит продаж'
                        ? 'p-2 w-36 text-white bg-red-xit'
                        : category.status === 'Популярное'
                        ? 'p-2 w-36 text-white bg-yellow-popular'
                        : category.status === 'Pекомендуем'
                        ? 'p-2 w-36 text-white bg-blue-recommend'
                        : category.status === '-17% скидка'
                        ? 'p-2 w-36 text-white bg-red-sale'
                        : category.status === 'Новинки'
                        ? 'p-2 w-36 text-white bg-green-new'
                        : ''
                    }
                  >
                    {category.status}
                  </li>
                </ul>
              </div>
            )
          })}
      </div>
    </div>
  )

}
